[versions]
wpilib = "2026.+"
photonlib = "v2026.0.1"
photontargeting = "v2026.0.1"
ctre = "26.1.0"
pathplanner = "2026.1.2"
choreo = "2025.0.3"
rev = "2026.0.1"
studica = "2025.0.1"
jackson = "2.17.2"
ejml = "0.43.1"
opencv = "4.10.0-3"
