[versions]
wpilib = "2026.+"
photonlib = "v2026.0.0"
photontargeting = "v2026.0.0"
ctre = "26.0.0"
pathplanner = "2026.0.0"
choreo = "2026.0.0"
rev = "2026.0.0"
studica = "2026.0.0"
jackson = "2.17.2"
ejml = "0.43.1"
opencv = "4.10.0-3"
