[versions]
wpilib = "2026.+"
photonlib = "v2025.2.1"
photontargeting = "v2025.2.1"
ctre = "25.1.0"
pathplanner = "2025.1.1"
choreo = "2025.0.3"
rev = "2025.0.0"
studica = "2025.0.1"
jackson = "2.17.2"
ejml = "0.43.1"
opencv = "4.10.0-3"
